FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o websocket-service ./cmd/main.go

FROM alpine:3.19

WORKDIR /app
COPY --from=builder /app/websocket-service .

EXPOSE 9000
CMD ["./websocket-service"]
