FROM golang:1.21-alpine AS builder
WORKDIR /src
COPY . .
RUN apk add --no-cache git
RUN go build -o /bin/message-service ./cmd

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/message-service /bin/message-service
COPY config.yaml /app/config.yaml
WORKDIR /app
EXPOSE 8085
CMD ["/bin/message-service"]
