FROM golang:1.21-alpine AS build
WORKDIR /src
COPY . .
RUN go build -o /bin/ws-service ./cmd/ws-service

FROM alpine:3.18
COPY --from=build /bin/ws-service /bin/ws-service
EXPOSE 8081
CMD ["/bin/ws-service"]
