FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o message-service ./cmd/main.go

FROM alpine:3.19

WORKDIR /app
COPY --from=builder /app/message-service .

EXPOSE 8004
CMD ["./message-service"]
